server:
  port: 8761

spring:
  profiles:
    active: @profiles.active@
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: discovery    # 项目名称尽量用小写

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true